### ISSUE TITLE
Add NavBar in small screen

### ISSUE THREAD

**Issue by shashankcoc** [mozilla/awebpodcast#39]
Adding navbar can give website a great look

**Comment by stephaniehobson** [comment]
Hi @shashankcoc thanks for the ideas but there are no resources devoted to IRL right now. So we can't implement ideas and we can't review pull requests. I'll bring it up with the team if we do a Season 6 :)

**Comment by shashankcoc** [comment]
Ok @stephaniehobson sure 👍
