### ISSUE TITLE
No links for Facebook Github and all

### ISSUE THREAD

**Issue by shashankcoc** [mozilla/awebpodcast#40]
Adding These links to footer will be great
@glogiotatidis

**Comment by stephaniehobson** [comment]
Hi @shashankcoc thanks for the ideas but there are no resources devoted to IRL right now. So we can't implement ideas and we can't review pull requests. I'll bring it up with the team if we do a Season 6 :)

**Comment by shashankcoc** [comment]
Hey @stephaniehobson  ok sure👍
